version: '3.3'

services:
  bamboo_server:
    image: bamboo_server
    build: ./bamboo_server
    container_name: bamboo_server
    depends_on:
      - postgresql_server
    ports:
      - target: 8085
        published: 8085
        protocol: tcp
        mode: host
      - target: 54663
        published: 54663
        protocol: tcp
        mode: host
    environment:
      # https://bitbucket.org/atlassian-docker/docker-bamboo-server/src/master/entrypoint.py
      - RUN_USER=root
      - RUN_GROUP=root
      - ATL_PROXY_NAME=${PROXY_HOSTNAME}
      - ATL_PROXY_PORT=${PROXY_PORT}
      - ATL_AUTOLOGIN_COOKIE_AGE=86400
      - BAMBOO_HOME=/var/atlassian/application-data/bamboo
      - ATL_BROKER_URI=nio://0.0.0.0:54663
      - ATL_BROKER_CLIENT_URI=failover:(tcp://${PROXY_HOSTNAME}:54663?wireFormat.maxInactivityDuration=300000)
      - ATL_BAMBOO_SKIP_CONFIG=true
      - ATL_BAMBOO_ENABLE_UNATTENDED_SETUP=true
      - ATL_BAMBOO_DISABLE_AGENT_AUTH=false
      - SECURITY_TOKEN=${BAMBOO_SECURITY_TOKEN}
      - ATL_LICENSE=${BAMBOO_LICENSE}
      - ATL_BASE_URL=https://${PROXY_HOSTNAME}
      - ATL_ADMIN_USERNAME=${BAMBOO_ADMIN_USERNAME}
      - ATL_ADMIN_PASSWORD=${BAMBOO_ADMIN_PASSWORD}
      - ATL_ADMIN_FULLNAME=${BAMBOO_ADMIN_FULLNAME}
      - ATL_ADMIN_EMAIL=${BAMBOO_ADMIN_EMAIL}
      - ATL_IMPORT_OPTION=clean
      - ATL_IMPORT_PATH=
      - ATL_FORCE_CFG_UPDATE=true
      - ATL_DB_TYPE=${DB_TYPE}
      - ATL_JDBC_URL=jdbc:postgresql://bamboo_postgresql:5432/${DB_NAME}
      - ATL_JDBC_USER=${DB_USER}
      - ATL_JDBC_PASSWORD=${DB_PASSWORD}
    volumes:
      #- ${PWD}/bamboo_data:/var/atlassian/application/application-data/bamboo:rw
      - ${PWD}/bamboo_home:/var/atlassian/application-data/bamboo:rw

  postgresql_server:
    image: postgres:14.5
    container_name: bamboo_postgresql
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - bamboo_postgresql:/var/lib/postgresql/data:rw

volumes:
  bamboo_postgresql:
    driver: local
