version: '3.3'

services:
  nginx_proxy:
    image: nginx_proxy
    build: ./nginx_proxy
    container_name: nginx_proxy
    healthcheck:
      test: [ "CMD", "curl", "-s", "-k", "https://${PROXY_HOSTNAME}:${PROXY_PORT}/rest/api/latest/status" ]
      timeout: 5s
      interval: 30s
      retries: 3
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: ${PROXY_PORT}
        protocol: tcp
        mode: host
    environment:
      - NGINX_HOST=${PROXY_HOSTNAME}
      - NGINX_PORT=${PROXY_PORT}
      - NGINX_UPSTREAM_HOST=${BAMBOO_HOSTNAME}
      - NGINX_UPSTREAM_PORT=${BAMBOO_PORT}
    links:
      - bamboo_server

  bamboo_server:
    image: bamboo_server
    build:
      context: ./bamboo_server
      args:
        - DOCKER_GID=${BAMBOO_HOST_DOCKER_GID}
    container_name: bamboo_server
    healthcheck:
      test: [ "CMD", "curl", "-s", "http://localhost:${BAMBOO_PORT}/rest/api/latest/status" ]
      timeout: 5s
      interval: 30s
      retries: 6
    restart: unless-stopped
    depends_on:
      - postgresql_server
    ports:
      - target: ${BAMBOO_PORT}
        published: ${BAMBOO_PORT}
        protocol: tcp
        mode: host
      - target: 54663
        published: 54663
        protocol: tcp
        mode: host
    environment:
      # https://bitbucket.org/atlassian-docker/docker-bamboo-server/src/master/entrypoint.py and
      # https://bitbucket.org/atlassian-docker/docker-shared-components/src/master/image/entrypoint_helpers.py
      - RUN_USER=${BAMBOO_USER}
      - RUN_GROUP=${BAMBOO_GROUP}
      - ATL_PROXY_NAME=${PROXY_HOSTNAME}
      - CATALINA_CONNECTOR_PROXYNAME=${PROXY_HOSTNAME}
      - ATL_PROXY_PORT=${PROXY_PORT}
      - CATALINA_CONNECTOR_PROXYPORT=${PROXY_PORT}
      - ATL_PROXY_SCHEME=${PROXY_SCHEME}
      - CATALINA_CONNECTOR_SCHEME=${PROXY_SCHEME}
      - ATL_PROXY_SECURE=${PROXY_SECURE}
      - CATALINA_CONNECTOR_SECURE=${PROXY_SECURE}
      - ATL_TOMCAT_MGMT_PORT=8007
      - ATL_TOMCAT_PORT=${BAMBOO_PORT}
      - ATL_AUTOLOGIN_COOKIE_AGE=86400
      - BAMBOO_HOME=/var/atlassian/application-data/bamboo
      - ATL_BROKER_URI=nio://0.0.0.0:54663
      - ATL_BROKER_CLIENT_URI=failover:(tcp://${PROXY_HOSTNAME}:54663?wireFormat.maxInactivityDuration=300000)
      - ATL_BAMBOO_SKIP_CONFIG=true
      - ATL_BAMBOO_ENABLE_UNATTENDED_SETUP=true
      - ATL_BAMBOO_DISABLE_AGENT_AUTH=false
      - SECURITY_TOKEN=${BAMBOO_SECURITY_TOKEN}
      - ATL_LICENSE=${BAMBOO_LICENSE}
      - ATL_BASE_URL=https://${PROXY_HOSTNAME}
      - ATL_ADMIN_USERNAME=${BAMBOO_ADMIN_USERNAME}
      - ATL_ADMIN_PASSWORD=${BAMBOO_ADMIN_PASSWORD}
      - ATL_ADMIN_FULLNAME=${BAMBOO_ADMIN_FULLNAME}
      - ATL_ADMIN_EMAIL=${BAMBOO_ADMIN_EMAIL}
      - ATL_IMPORT_OPTION=clean
      - ATL_IMPORT_PATH=
      - ATL_FORCE_CFG_UPDATE=true
      - ATL_DB_TYPE=${DB_TYPE}
      - ATL_JDBC_URL=jdbc:postgresql://bamboo_postgresql:5432/${DB_NAME}
      - ATL_JDBC_USER=${DB_USER}
      - ATL_JDBC_PASSWORD=${DB_PASSWORD}
    volumes:
      - /var/run/docker.sock:${BAMBOO_HOST_DOCKER_SOCKET}
      - ${PWD}/bamboo_home:/var/atlassian/application-data/bamboo:rw

  postgresql_server:
    image: postgres:14.5
    container_name: bamboo_postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      timeout: 5s
      interval: 10s
      retries: 3
    restart: unless-stopped
    ports:
      - target: 5432
        published: ${DB_PORT}
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - bamboo_postgresql:/var/lib/postgresql/data:rw

volumes:
  bamboo_postgresql:
    driver: local
