version: '3.3'

services:
  bamboo_server:
    image: bamboo_server
    build: ./bamboo_server
    container_name: bamboo_server
    depends_on:
      - postgresql_server
    ports:
      - target: 8085
        published: 8085
        protocol: tcp
        mode: host
    environment:
      - ATL_PROXY_NAME=mblomdahl-mkdevops-se-bamboo-ci-health-7gwq6wr562p5qw-8085.githubpreview.dev
      - ATL_PROXY_PORT=443
      - ATL_LICENSE=AAA...02kc
      - ATL_JDBC_URL=jdbc:postgresql://bamboo_postgresql:5432
      - ATL_JDBC_USER=bamboouser
      - ATL_JDBC_PASSWORD=password
      - ATL_JDBC_TYPE=postgresql
    volumes:
      - bamboo_server:/var/atlassian/application/application-data/bamboo:rw

  postgresql_server:
    image: postgres:14.5
    container_name: bamboo_postgresql
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_DB=bamboo
      - POSTGRES_USER=bamboouser
      - POSTGRES_PASSWORD=password
    volumes:
      - bamboo_postgresql:/var/lib/postgresql/data:rw

volumes:
  bamboo_server:
    driver: local
  bamboo_postgresql:
    driver: local
